<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_CamDTDriver" Id="{691e79d7-fe42-48ae-bc38-5225fb2a0e85}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CamDTDriver	
VAR_INPUT
	Reset                                        :BOOL; //复位     
   	bCamInExecute			                :BOOL;	//凸轮耦合启动
   	bCreatTable		                        :BOOL;	//凸轮阶建启动
	iTable		                              :UINT;   //凸轮表号    
    fMainPos                                  :REAL;//叠台到位主轴的角度
    fbStartingPoint                           :REAL;//叠台凸轮的起点
	fbEndPoint								  :REAL;//叠台凸轮的终点
	fbCenterPoint								:REAL;//叠台压刀外边到过辊的中心距离
	
END_VAR
VAR_IN_OUT
	axisSlave		                    :axis_ref;  //从轴
	axisMaster		                    :axis_ref;  //主轴
	arrTableData: ARRAY[0..3600,0..1] OF LREAL;//叠台凸轮数据
END_VAR

VAR_OUTPUT
	Master_MidPos: LREAL;// 叠台压好到过辊中分主轴相位
	iFend: INT;// 叠台压刀到过辊中心主轴相位对应的索引	
    bCreatTableDone         :BOOL;//凸轮创建完成
    bCreatTableError         :BOOL;//凸轮创建错误
	bError                         :BOOL;//报警
	bReady                        :BOOL;//准备OK
	bInSync		                   :BOOL;//凸轮耦合中
END_VAR


VAR
	fbCamInSlave: MC_CamIn;
	fbCamOut: MC_CamOut;
	fbHaltSlave: MC_Halt; 
	rtrigs		:ARRAY[1..3]OF R_TRIG;
	ftrigs		:ARRAY[1..3]OF F_TRIG;
	iCamInStep: UINT;
	 PositionData			:	ARRAY[1..4] OF MC_MotionFunctionPoint;	
     PositionData1			:	ARRAY[1..4] OF MC_MotionFunctionPoint;	

	fbCamtableselect:			MC_CamTableSelect;
	Cam_table:				MC_CAM_REF;
    CamTable_MF:             MC_CAM_REF;

	rtError:  Tc2_Standard.R_TRIG;  	

    fbChangeCamModeSetOut	:	Tc2_MC2.ST_McOutputs;

	MA1: BOOL;
   fbCamInOut:                       Tc2_MC2.ST_McOutputs;
   bPoints :ARRAY[1..5] OF MC_MotionFunctionPoint; 
   mcReadMotionFunction: MC_ReadMotionFunction;
   mcReadMotionFunctionOut:Tc2_MC2.ST_McOutputs;
	iCreatTableStep: INT;
	fbHaltMaster: INT;
	bWriteCamData: BOOL;
	fSlavePos1: REAL;
	fSlavePos2: REAL;
	// 叠台移动的距离
	fBeltSpacePos: REAL;
	// 叠台中心点，主轴相位计算
	ReadPointVelues: BOOL;
	i: INT;
	Test_int: INT;
	mcReadMotionFunctionValues: MC_ReadMotionFunctionValues;
	CamTable: MC_CAM_REF;
	// 叠台凸轮数据读取完成
	arrReadPosDone: BOOL;
	rtRead: R_TRIG;
	ftRead: F_TRIG;	
	CamTable1: MC_CAM_REF;
	CamTable2: MC_CAM_REF;
	mcReadMotionFunctionValues_Busy: BOOL;
	mcReadMotionFunctionValues_Error: BOOL;
	mcReadMotionFunctionValues_ErrorID: UDINT;
	FB_ReadCamarrPos1: FB_ReadCamarrPos;
	arrReadPosDone1: BOOL;
	arrTableData1: ARRAY [0..3600, 0..1] OF LREAL;
	mcReadMotionFunctionValues1: MC_ReadMotionFunctionValues;
	CamTable3: MC_CAM_REF;
	TEST: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[rtrigs[1](CLK:=bCreatTable);  
ftrigs[1](CLK:=bCreatTable);  




CASE iCreatTableStep OF   
0:  
    IF  NOT bInSync  AND  rtrigs[1].Q  AND NOT bCreatTableError  THEN
         fbCamtableselect.Execute:=FALSE;
         bCreatTableDone:=FALSE;
         bCreatTable:=FALSE;
         bWriteCamData:=TRUE;
		 ReadPointVelues:=FALSE;
         iCreatTableStep:=10;
    END_IF 
10: //节点写入完成
   IF NOT bWriteCamData THEN 
	  fbCamtableselect.Execute:=TRUE;     
	 iCreatTableStep:=20;	
  END_IF
20:	//凸轮生成	
	IF NOT  fbCamtableselect.Execute     THEN
        //bCreatTableDone:=TRUE;
		iCreatTableStep:=30;	
    ELSIF  fbCamtableselect.Error THEN
       bCreatTableError:=TRUE;
       iCreatTableStep:=999;	//创建凸轮失败
	END_IF	
30:
		ReadPointVelues:=TRUE;
		IF arrReadPosDone THEN
			bCreatTableDone:=TRUE;
			ReadPointVelues:=FALSE;
			iCreatTableStep:=0;
		ELSIF mcReadMotionFunctionValues1.Error THEN
       		bCreatTableError:=TRUE;
       		iCreatTableStep:=999;	//创建凸轮失败			
		END_IF	
END_CASE	
(**********故障***********)
	IF  Reset  AND bCreatTableError  THEN  
	   bCreatTableError:=FALSE;
	   iCreatTableStep:=0;
	END_IF
(*****************************************耦合***************************************)
fbCamInSlave.BufferMode;
fbCamInSlave.Options.ActivationMode;
fbCamInSlave.Options.ActivationPosition;
fbCamInSlave.Options.ActivationMode;
fbCamInSlave.Options.InterpolationType;
fbCamInSlave.Options.MasterScalingMode;
fbCamInSlave.Options.SlaveScalingMode;

(************************************  相关状态  *************************************************)
bReady:= axisSlave.Status.ControlLoopClosed  AND axisMaster.Status.ControlLoopClosed AND  
               NOT bInSync  AND NOT bError   AND  bCreatTableDone   ;  

rtrigs[2](CLK:=bCamInExecute);  
ftrigs[2](CLK:=bCamInExecute);  

CASE iCamInStep OF
0:  
      fbCamInSlave.MasterOffset:=0;
      fbCamInSlave.SlaveOffset:=0;
      fbCamtableselect.Execute:=FALSE;
   	  fbCamInSlave.Execute:=FALSE;
	  fbCamOut.Execute:=FALSE;
	  fbHaltSlave.Execute:=FALSE;
      iCreatTableStep:=0;
      iCamInStep:=10;
10:
  IF bCamInExecute  AND  bReady THEN //耦合
	   iCamInStep:=100;
  ELSIF ftrigs[2].Q THEN  //解耦
	    iCamInStep:=200;
 ELSIF bInSync AND NOT bCamInExecute THEN
        iCamInStep:=200;
  END_IF

100:(**凸轮耦合**)
      fbCamInSlave.Execute:=TRUE;
      iCamInStep:=110;
110:
    IF NOT  fbCamInSlave.Execute AND axisSlave.Status.Coupled THEN
        bInSync:=TRUE;  //同步状态输出
        iCamInStep:=0;
   ELSIF fbCamInSlave.Error OR fbCamInSlave.CommandAborted THEN
         iCamInStep:=999;
    END_IF

(**********************解耦  *******************************)
200:
		fbCamOut.Execute:=TRUE;
		iCamInStep:=210;
210: 
	IF  NOT axisSlave.Status.Coupled   THEN 
	  	fbHaltSlave.Execute:=TRUE; 
	 	iCamInStep:=220;
    ELSIF  fbCamOut.Error  THEN
        iCamInStep:=999;
	END_IF
220: 
	IF axisSlave.Status.NotMoving    THEN
		bInSync:=FALSE; //同步状态输
		iCamInStep:=0;
     ELSIF fbHaltSlave.Error OR fbHaltSlave.CommandAborted THEN
          iCamInStep:=999;
	END_IF
END_CASE

(**********故障复位***********)
	IF  Reset  AND bError  THEN  
	   bError:=FALSE;
	   iCamInStep:=0;
	END_IF
rtError(CLK:=fbCamInSlave.Error  OR fbCamOut.Error OR fbHaltSlave.Error OR iCamInStep=999     , Q=> );
IF 	rtError.Q THEN
	bError:=TRUE;
	bInSync:=FALSE; //同步状态输
END_IF


Motion();      
ModifyCam();

]]></ST>
    </Implementation>
    <Action Name="ModifyCam" Id="{a41f5caa-fb74-4326-8cff-abe2d4f7a6dd}">
      <Implementation>
        <ST><![CDATA[//凸轮创建
fbCamtableselect(   
	Execute:=                        fbCamtableselect.Execute ,
	Periodic:=                       TRUE ,
	MasterAbsolute:=             FALSE,//
	SlaveAbsolute:=                FALSE ,//
	CamTableID:=                  iTable,
	Master:=                         axisMaster ,
	Slave:=                            axisSlave ,
	CamTable:=                     Cam_table , );
IF fbCamtableselect.Done THEN
    fbCamtableselect.Execute:=FALSE;
END_IF
//凸轮关键点写入
IF bWriteCamData  THEN    //98     初始点   90
	  Cam_table.ArraySize:=SIZEOF(PositionData1); 
	  Cam_table.NoOfColumns:=1;
	  Cam_table.NoOfRows:=3;
	  Cam_table.pArray:=ADR(PositionData1);
	  Cam_table.TableType:=MC_TABLETYPE_MOTIONFUNCTION;
  
	  fBeltSpacePos:=fbEndPoint-fbStartingPoint;
	  
	  PositionData1[1].	PointIndex	:=	        1;
	  PositionData1[1].	FunctionType	:=		MOTIONFUNCTYPE_POLYNOM7_MM;
	  PositionData1[1].	PointType	:=	        MOTIONPOINTTYPE_MOTION;
	  PositionData1[1].	RelIndexNextPoint	:=  1;
	  PositionData1[1].	MasterPos	:=	        0;
	  PositionData1[1].	SlavePos	:=	        0;		
	  PositionData1[1].	SlaveVelo	:=	        0;
	  
	  PositionData1[2].	PointIndex	:=	        2;
	  PositionData1[2].	FunctionType	:=		MOTIONFUNCTYPE_POLYNOM1;
	  PositionData1[2].	PointType	:=	        MOTIONPOINTTYPE_MOTION;
	  PositionData1[2].	RelIndexNextPoint	:=  1;
	  PositionData1[2].	MasterPos	:=	        fMainPos;
	  PositionData1[2].	SlavePos	:=	        fBeltSpacePos;	
	  PositionData1[2].	SlaveVelo	:=	        0	;
	  
	  PositionData1[3].	PointIndex	:=	        3;
	  PositionData1[3].	FunctionType	:=		MOTIONFUNCTYPE_POLYNOM7_MM;
	  PositionData1[3].	PointType	:=	        MOTIONPOINTTYPE_MOTION;
	  PositionData1[3].	RelIndexNextPoint	:=  0;
	  PositionData1[3].	MasterPos	:=	        360;
	  PositionData1[3].	SlavePos	:=	        fBeltSpacePos;	
	  PositionData1[3].	SlaveVelo	:=	       0;
   
     bWriteCamData:=FALSE;
END_IF


//读取叠台的数据
rtRead(CLK:=ReadPointVelues , Q=> );
ftRead(CLK:=ReadPointVelues , Q=> );	
	IF rtRead.Q THEN
		mcReadMotionFunctionValues.Execute:=TRUE;
		CamTable3.pArray:=ADR(arrTableData);
		CamTable3.ArraySize:=SIZEOF(arrTableData);
		CamTable3.NoOfColumns:=2;
		CamTable3.NoOfRows:=3601;
		CamTable3.TableType:=10;	
	END_IF	
	 mcReadMotionFunctionValues1(
		  Execute:=                          mcReadMotionFunctionValues.Execute , 
		  CamTableID:=                   iTable , 
		  ValueSelectMask:=               1 ,
		  StartPosMaster:=               0 , 
		  EndPosMaster:=                360 , //360
		  Increment:=                       0.1 , 
		  Done=>                           arrReadPosDone , 
		  Busy=>mcReadMotionFunctionValues_Busy                              , 
		  Error=>mcReadMotionFunctionValues_Error                             , 
		  ErrorID=>mcReadMotionFunctionValues_ErrorID                         , 
		  CamTable:=                      CamTable3      );
	IF ftRead.Q THEN
		mcReadMotionFunctionValues.Execute:=FALSE;	
	END_IF	
//叠台中心点，主轴相位计算 fbCenterPoint
	Test_int:=REAL_TO_INT(fMainPos*10);
	FOR	i:=0 TO Test_int BY 1  DO
		IF (fbCenterPoint-0.15)< arrTableData[i,1] AND arrTableData[i,1]<(fbCenterPoint +0.15) THEN
			iFend:=i;
			Master_MidPos:=arrTableData[i,0];			
		END_IF		
	END_FOR
	
	
	
	
	
	
	
	
	]]></ST>
      </Implementation>
    </Action>
    <Action Name="Motion" Id="{167d9c9a-345a-4515-a834-d57fd96a99a3}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"fbCamInSlave.Execute"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">3</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">31L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_CamIn"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"fbCamInSlave"</v>
                            <v n="Type">"MC_CamIn"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">2L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">"fbCamInOut.Busy"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">4L</v>
                              </o>
                              <o>
                                <v n="Operand">"fbCamInOut.Active"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">5L</v>
                              </o>
                              <o>
                                <v n="Operand">"fbCamInOut.CommandAborted"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">6L</v>
                              </o>
                              <o>
                                <v n="Operand">"fbCamInOut.CommandAborted"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">7L</v>
                              </o>
                              <o>
                                <v n="Operand">"fbCamInOut.ErrorID"</v>
                                <v n="Type">"UDINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">8L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"axisMaster"</v>
                                <v n="Type">"axis_ref"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">10L</v>
                              </o>
                              <v n="Id">9L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"axisSlave"</v>
                                <v n="Type">"axis_ref"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">12L</v>
                              </o>
                              <v n="Id">11L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"fbCamInSlave.Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">14L</v>
                              </o>
                              <v n="Id">13L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"fbCamInSlave.MasterOffset"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">16L</v>
                              </o>
                              <v n="Id">15L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"fbCamInSlave.SlaveOffset"</v>
                                <v n="Type">"LREAL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">18L</v>
                              </o>
                              <v n="Id">17L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"1"</v>
                                <v n="Type">"INT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">20L</v>
                              </o>
                              <v n="Id">19L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"1"</v>
                                <v n="Type">"INT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">22L</v>
                              </o>
                              <v n="Id">21L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"MC_StartMode.MC_STARTMODE_RELATIVE"</v>
                                <v n="Type">"MC_STARTMODE"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">24L</v>
                              </o>
                              <v n="Id">23L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"iTable"</v>
                                <v n="Type">"UINT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">26L</v>
                              </o>
                              <v n="Id">25L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"fbCamInSlave.BufferMode"</v>
                                <v n="Type">"MC_BufferMode"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">28L</v>
                              </o>
                              <v n="Id">27L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"fbCamInSlave.Options"</v>
                                <v n="Type">"ST_CamInOptions"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">30L</v>
                              </o>
                              <v n="Id">29L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Master</v>
                              <v>Slave</v>
                              <v>Execute</v>
                              <v>MasterOffset</v>
                              <v>SlaveOffset</v>
                              <v>MasterScaling</v>
                              <v>SlaveScaling</v>
                              <v>StartMode</v>
                              <v>CamTableID</v>
                              <v>BufferMode</v>
                              <v>Options</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>AXIS_REF[REF]</v>
                              <v>AXIS_REF[REF]</v>
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>MC_StartMode</v>
                              <v>MC_CAM_ID</v>
                              <v>MC_BufferMode</v>
                              <v>ST_CamInOptions</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>InSync</v>
                              <v>Busy</v>
                              <v>Active</v>
                              <v>CommandAborted</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">3L</v>
                        </o>
                        <v n="Id">32L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"fbCamOut.Execute"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">3</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">45L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_CamOut"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"fbCamOut"</v>
                            <v n="Type">"MC_CamOut"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">34L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">36L</v>
                              </o>
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">37L</v>
                              </o>
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">38L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"fbCamOut.Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">40L</v>
                              </o>
                              <v n="Id">39L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">42L</v>
                              </o>
                              <v n="Id">41L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"axisSlave"</v>
                                <v n="Type">"axis_ref"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">44L</v>
                              </o>
                              <v n="Id">43L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Execute</v>
                              <v>Options</v>
                              <v>Slave</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>ST_CamOutOptions</v>
                              <v>AXIS_REF</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">35L</v>
                        </o>
                        <v n="Id">46L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">33L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"fbHaltSlave.Execute"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">3</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">67L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"MC_Halt"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"fbHaltSlave"</v>
                            <v n="Type">"MC_Halt"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">48L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">50L</v>
                              </o>
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">51L</v>
                              </o>
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">52L</v>
                              </o>
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">53L</v>
                              </o>
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">54L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"fbHaltSlave.Execute"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">56L</v>
                              </o>
                              <v n="Id">55L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">58L</v>
                              </o>
                              <v n="Id">57L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">60L</v>
                              </o>
                              <v n="Id">59L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">62L</v>
                              </o>
                              <v n="Id">61L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">64L</v>
                              </o>
                              <v n="Id">63L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"axisSlave"</v>
                                <v n="Type">"axis_ref"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">66L</v>
                              </o>
                              <v n="Id">65L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Execute</v>
                              <v>Deceleration</v>
                              <v>Jerk</v>
                              <v>BufferMode</v>
                              <v>Options</v>
                              <v>Axis</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>LREAL</v>
                              <v>LREAL</v>
                              <v>MC_BufferMode</v>
                              <v>ST_MoveOptions</v>
                              <v>AXIS_REF</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Done</v>
                              <v>Busy</v>
                              <v>Active</v>
                              <v>CommandAborted</v>
                              <v>Error</v>
                              <v>ErrorID</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>BOOL</v>
                              <v>UDINT</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <n n="EN" />
                          <n n="ENO" />
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">49L</v>
                        </o>
                        <v n="Id">68L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">47L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <LineIds Name="FB_CamDTDriver">
      <LineId Id="266" Count="28" />
      <LineId Id="489" Count="1" />
      <LineId Id="493" Count="1" />
      <LineId Id="499" Count="1" />
      <LineId Id="496" Count="0" />
      <LineId Id="498" Count="0" />
      <LineId Id="497" Count="0" />
      <LineId Id="495" Count="0" />
      <LineId Id="298" Count="0" />
      <LineId Id="300" Count="4" />
      <LineId Id="307" Count="80" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_CamDTDriver.ModifyCam">
      <LineId Id="2" Count="9" />
      <LineId Id="13" Count="2" />
      <LineId Id="39" Count="7" />
      <LineId Id="96" Count="1" />
      <LineId Id="47" Count="28" />
      <LineId Id="162" Count="0" />
      <LineId Id="161" Count="0" />
      <LineId Id="187" Count="0" />
      <LineId Id="194" Count="0" />
      <LineId Id="188" Count="4" />
      <LineId Id="186" Count="0" />
      <LineId Id="144" Count="10" />
      <LineId Id="139" Count="0" />
      <LineId Id="166" Count="1" />
      <LineId Id="84" Count="0" />
      <LineId Id="99" Count="0" />
      <LineId Id="112" Count="0" />
      <LineId Id="100" Count="0" />
      <LineId Id="110" Count="0" />
      <LineId Id="172" Count="0" />
      <LineId Id="169" Count="1" />
      <LineId Id="111" Count="0" />
      <LineId Id="101" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>